spring:
  application:
    name: pos-deliver
  cloud:
      function:
        definition: makeDelivery
      stream:
        function:
          bindings:
            makeDelivery-in-0: deliver
        rabbit:
          bindings:
            deliver:
              destination: deliver
              consumer:
                declare-exchange: false

server:
  port: 45902
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}